import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useTranslation } from 'react-i18next'
import { useRouter } from 'next/router'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { t, i18n } = useTranslation()
  const router = useRouter()
  const { pathname, query, asPath } = router;

  /**
   * This function changes the language of the application and updates the router with the new language.
   * @param {any} lang - The `lang` parameter is a variable that represents the language code that the
   * user wants to switch to. It is passed as an argument to the `handelLanguageChange` function.
   */
  const handelLanguageChange = (lang: any) => {
    i18n.changeLanguage(lang, () => {
      router.replace({ pathname, query }, asPath, { locale: lang })
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            {t('index.getStarted')}&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <button onClick={() => handelLanguageChange("en")}>
            English
          </button>
          <button onClick={() => handelLanguageChange("ar")}>
            Arabic
          </button>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              {t('index.docs')} <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {t('index.docsMessage')}
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              {t('index.learn')} <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {t('index.learnMessage')}
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              {t('index.template')} <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {t('index.templateMessage')}
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              {t('index.deploy')} <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {t('index.deployMessage')}
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
